name: Deploy to Production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: |
        npm install
        npm run build

    - name: Upload to Production
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist

    - name: Deploy to Production
      uses: actions/download-artifact@v2
      with:
        name: dist
      run: |
        # Add your deployment commands here
        echo "Deploying to production..."
        scp -r ./dist/* shamak@shamak.ftp.tools:/home/shamak/shamak.tech/api/
