on: push
name: Deploy on Commit test
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node -v
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: ls
      - run: scp -r ./dist ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:${{ secrets.DEPLOY_PATH }}
      - run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "cd ${{ secrets.DEPLOY_PATH }} && npm install && npm start"
