name: Deploy to Production

on: [push, workflow_dispatch]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: |
        npm install
        npm run build

    - name: Upload to Production
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
      
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: distfiles

    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.0.3
      with:
      
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "distfiles/*"
        target: ${{ secrets.PATH }}
        script: |
          echo "DONE" 
