on: push
name: Deploy on Commit test
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node -v
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: ls
      - run: scp -r ./dist rival-clash@154.49.136.221:/home/dshamak/
      - run: ssh rival-clash@154.49.136.221 "cd /home/dshamak/ && npm install && npm start"
