name: Deployment Workflow
on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        uses: ilCollez/ssh-scp-deploy@v1.3.0
          with:
              host: ${{ secrets.HOST }} # "example.com"
              username: ${{ secrets.USER }} # "user"
              key: ${{ secrets.PRIVATE_KEY }} # you can also use key-path: "~/.ssh/id_rsa"
              passphrase: ${{ secrets.PASSPHRASE }} # "passphrase"
              files: |
                  *.json
                  public
                  dist
              remote-path: ${{ secrets.PATH }}